name: .NET Core
env:
    DOTNET_ROOT: /usr/share/dotnet
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -r win-x64 -c Release
    - name: Upload DevOpsContentful Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DevOpsContentful.exe
        path: /DevOpsContentful/bin/Release/netcoreapp3.1/
    - name: Show contents of the current working directory
      run: ls -R
