name: .NET Core

on: [push]

jobs:
  buildpackage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build dotnet
      run: dotnet build --configuration Release
    - name: dotnet puglish
      run: dotnet publish -r win-x64 -c Release -o ${{env.DOTNET_ROOT}}/DevOpsContentful

    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: .dotnet-DevOpsContentful
        path: ${{env.DOTNET_ROOT}}/
    
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Build
      run: docker build -t ${{ secrets.DOCKER_USER }}/devopscontentful:latest .
    - name: Upload container to Docker Hub with Push
      run: docker push ${{ secrets.DOCKER_USER }}/devopscontentful:latest
